name: personal_portfolio
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.2.6
  js: ^0.6.7
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.7.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/profile.jpg
    - assets/mongodb_course.jpg
    - assets/asyncjavascript.jpg
    - assets/tic_tac_toe.png
    - assets/mealdb_app.png
    - assets/idcard.png
    - assets/grocery_app.png

  
        
